# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 15.0
      uses: actions/setup-node@v3
      with:
        node-version: 15.0.1
    - run: npm install
    - run: npm run lint
    - run: npm install -g prettier
    - run: npm run prettier
    - run: npm run build
